### ISSUE TITLE
Weird Issue

### ISSUE THREAD

**Issue by klept0** [Krazalm/MonopolyGoBotCustomedited#3]
Getting this as a random error on both the original and your version on 2 different machines - any suggestion as to what to look at?

```
Monopoly Go! Bot

Press Key.f2 to toggle running.

Started

2023-12-02 03:27:47,547 - INFO - Bot started.
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\pyautogui\__init__.py", line 172, in wrapper
    return wrappedFunction(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pyautogui\__init__.py", line 204, in locateCenterOnScreen
    return pyscreeze.locateCenterOnScreen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pyscreeze\__init__.py", line 447, in locateCenterOnScreen
    coords = locateOnScreen(image, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pyscreeze\__init__.py", line 405, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pyscreeze\__init__.py", line 383, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pyscreeze\__init__.py", line 257, in _locateAll_opencv
    raise ImageNotFoundException('Could not locate the image (highest confidence = %.3f)' % result.max())
pyscreeze.ImageNotFoundException: Could not locate the image (highest confidence = 0.425)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\klept\Desktop\MonopolyGoBotCustomedited-main\main.py", line 85, in <module>
    main()
  File "C:\Users\klept\Desktop\MonopolyGoBotCustomedited-main\main.py", line 82, in main
    MonopolyBot()
  File "C:\Users\klept\Desktop\MonopolyGoBotCustomedited-main\main.py", line 32, in __init__
    self.process_images()
  File "C:\Users\klept\Desktop\MonopolyGoBotCustomedited-main\main.py", line 53, in process_images
    if self.process_image(path):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\klept\Desktop\MonopolyGoBotCustomedited-main\main.py", line 70, in process_image
    point = self.find(image)
            ^^^^^^^^^^^^^^^^
  File "C:\Users\klept\Desktop\MonopolyGoBotCustomedited-main\main.py", line 65, in find
    result = pyautogui.locateCenterOnScreen(image, grayscale=True, confidence=CONFIDENCE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pyautogui\__init__.py", line 174, in wrapper
    raise ImageNotFoundException  # Raise PyAutoGUI's ImageNotFoundException.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyautogui.ImageNotFoundException
```

**Comment by klept0** [comment]
Looks like it was due to where the game screen was on the actual screen - once I moved it around it found a general happy place
