### ISSUE TITLE
How to actually start it

### ISSUE THREAD

**Issue by wowwwthanks** [Krazalm/MonopolyGoBotCustomedited#5]

**Comment by ThunderNRW** [comment]
How i can fix it ?

PS C:\monopolygobot> python main.py
Monopoly Go! Bot

Press Key.f2 to toggle running.

Started

2023-12-27 15:51:17,184 - INFO - Bot started.
Traceback (most recent call last):
  File "C:\Users\patri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyautogui\__init__.py", line 172, in wrapper
    return wrappedFunction(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyautogui\__init__.py", line 204, in locateCenterOnScreen
    return pyscreeze.locateCenterOnScreen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyscreeze\__init__.py", line 447, in locateCenterOnScreen
    coords = locateOnScreen(image, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyscreeze\__init__.py", line 405, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyscreeze\__init__.py", line 383, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyscreeze\__init__.py", line 257, in _locateAll_opencv
    raise ImageNotFoundException('Could not locate the image (highest confidence = %.3f)' % result.max())
pyscreeze.ImageNotFoundException: Could not locate the image (highest confidence = 0.445)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\monopolygobot\main.py", line 85, in <module>
    main()
  File "C:\monopolygobot\main.py", line 82, in main
    MonopolyBot()
  File "C:\monopolygobot\main.py", line 32, in __init__
    self.process_images()
  File "C:\monopolygobot\main.py", line 53, in process_images
    if self.process_image(path):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\monopolygobot\main.py", line 70, in process_image
    point = self.find(image)
            ^^^^^^^^^^^^^^^^
  File "C:\monopolygobot\main.py", line 65, in find
    result = pyautogui.locateCenterOnScreen(image, grayscale=True, confidence=CONFIDENCE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyautogui\__init__.py", line 174, in wrapper
    raise ImageNotFoundException  # Raise PyAutoGUI's ImageNotFoundException.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyautogui.ImageNotFoundException
PS C:\monopolygobot>
